### ISSUE TITLE
django 1.9.x compatibility

### ISSUE THREAD

**Issue by schoera** [bitmazk/django-document-library#3]
with django 1.9.2 I run into an ImportError:

> File "/[path-to-site-packages]/document_library/models.py", line 5, in <module>
>     from django.contrib.contenttypes import generic
> ImportError: cannot import name generic

In django 1.9: "The django.contrib.contenttypes.generic module is removed." (see [release notes](https://docs.djangoproject.com/en/1.9/releases/1.9/#features-removed-in-1-9))
So the imports need to be more concrete:

a) models.py
the used GenericForeignKey class now lives in the fields package, so importing the class from there will do the trick:
`from django.contrib.contenttypes.fields import GenericForeignKey`

b) admin.py
GenericTabularInline 
`from django.contrib.contenttypes.admin import GenericTabularInline`

hope this helps ...

**Comment by Tyrdall** [comment]
Done in 1.5.3 :)

https://github.com/bitmazk/django-document-library/commit/5112296a33e850df556aa9386791303da00d823b

**Comment by schoera** [comment]
thanx for the fast reaction
